version: '3.1'

services:

  php:
    image: php:7.0-apache
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /home/boneff/PhpstormProjects/battleship:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true

  phpunit:
    image: phpunit/phpunit # our PHPUnit image, created or found on Docker Hub
    volumes:
      - /home/boneff/PhpstormProjects/battleship:/var/www/html # folder where project resides. Should have same path
